# Setup
title:               Sonomama 
tagline:             "John Bauer's Blog" 
description:         'I am a Business Informatics interested in IT Security.'
url:                 'https://sono-mama.github.io/' 
baseurl:             '/blog'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              John Bauer 
  url:               
  email:             johnbauerberlin@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
